### ISSUE TITLE
play-services-analytics is deprecated

### ISSUE THREAD

**Issue by mohammadalijf** [adjust/react_native_sdk#167] opened 2022-04-01 14:34 UTC
In the sdk documention, In order for sdk to work it is required to use [Google Adverting ID](https://github.com/adjust/react_native_sdk#google-play-services). However, On [google play services](https://developers.google.com/android/guides/setup) it is mentioned that `play-services-analytics` is deprecated and we should use Firebase Analytics instead. My question is, If I use Firebase analytics instead of google play services analytics, does it break the Adjust SDK? or they share same API.

Also latest version of play-services-analytics is 18.0.1, Can I use the latest one instead (if it is not possible to use firbase analytics)?

![Screenshot 2022-04-01 at 16 27 18](https://user-images.githubusercontent.com/7884637/161284543-42eb2ddd-2a86-4f60-a985-91517503bbe6.png)

**Comment by uerceg** [comment] 2022-08-10 13:52
Hi @mohammadalijf,

Thank you for flagging this and seems like a duplicate of https://github.com/adjust/react_native_sdk/issues/182. Should be fixed now!

Cheers

**Closed by uerceg** 2022-08-10 13:52 UTC
